### ISSUE TITLE
Card Styling

### ISSUE THREAD

**Issue by caretcakejake** [barrotbake/Flash-Card-App#4]
Currently the cards look very bland, heres a mock of what they could look like

![image](https://user-images.githubusercontent.com/40745961/143796011-4b470bee-1cd8-4c40-b595-ab2b0f39d82c.png)

- [ ] Make it so card is more of an off-white color
- [ ] Round out the edges to make it look modern
- [ ] Add a shadow to the card to create some depth

**Comment by khoinguyen-hub** [comment]
@barrotbake may I work on this issue?

**Comment by caretcakejake** [comment]
@khoinguyen-hub go ahead!
